// @ts-nocheck
// This file is auto-generated by tauri-specta. Do not edit manually.
// Run `bun run dev` (debug build) to regenerate.

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async listProjects() : Promise<Result<Project[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_projects") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openProject(path: string) : Promise<Result<Project, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_project", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listSessions(projectId: string) : Promise<Result<Session[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_sessions", { projectId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listGroups() : Promise<Result<Group[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_groups") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createGroup(name: string) : Promise<Result<Group, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_group", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async renameGroup(groupId: string, name: string) : Promise<Result<Group, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rename_group", { groupId, name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteGroup(groupId: string) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_group", { groupId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setGroupLayout(groupId: string, layout: string) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_group_layout", { groupId, layout }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listGroupRoots(groupId: string) : Promise<Result<Project[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_group_roots", { groupId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listGroupSessions(groupId: string) : Promise<Result<Session[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_group_sessions", { groupId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Add a folder to a group as a root, opening/registering the project first.
 */
async addGroupRoot(groupId: string, path: string) : Promise<Result<Project, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_group_root", { groupId, path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeGroupRoot(groupId: string, projectId: string) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_group_root", { groupId, projectId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The repos a session pulls into context, primary first.
 */
async listSessionRoots(sessionId: string) : Promise<Result<Project[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_session_roots", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Replace a session's non-primary roots (selected from the group's roots).
 */
async setSessionRoots(sessionId: string, projectIds: string[]) : Promise<Result<Project[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_session_roots", { sessionId, projectIds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getWorktreeConfig(projectId: string) : Promise<Result<WorktreeConfig, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_worktree_config", { projectId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateWorktreeConfig(projectId: string, config: WorktreeConfig) : Promise<Result<WorktreeConfig, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_worktree_config", { projectId, config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getEvents(sessionId: string) : Promise<Result<EventRecord[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_events", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createSession(projectId: string, title: string, model: string, options: CreateSessionOptions) : Promise<Result<Session, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_session", { projectId, title, model, options }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Change a session's model, permission mode, and/or effort. Each field is
 * optional; omitted fields keep their current value. Applies to the next turn.
 */
async updateSession(sessionId: string, model: string | null, permissionMode: string | null, effort: string | null) : Promise<Result<Session, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_session", { sessionId, model, permissionMode, effort }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Toggle a session's git-worktree isolation. Only allowed before the first
 * turn — afterward the agent's conversation is tied to its working directory.
 */
async setSessionIsolation(sessionId: string, isolate: boolean) : Promise<Result<Session, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_session_isolation", { sessionId, isolate }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Re-run the repo's worktree setup commands for a session (after a failure,
 * or after the user edits the commands).
 */
async retryWorktreeSetup(sessionId: string) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("retry_worktree_setup", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Clear a failed setup state so the session is usable as-is.
 */
async dismissSetupError(sessionId: string) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("dismiss_setup_error", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Rename a session (its tab title).
 */
async renameSession(sessionId: string, title: string) : Promise<Result<Session, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rename_session", { sessionId, title }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Pin/unpin a session — pinned sessions sort to the top of the folder list.
 */
async setSessionPinned(sessionId: string, pinned: boolean) : Promise<Result<Session, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_session_pinned", { sessionId, pinned }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * A project's labels + which sessions each is attached to (one round-trip).
 */
async loadProjectLabels(projectId: string) : Promise<Result<ProjectLabels, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_project_labels", { projectId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createLabel(projectId: string, name: string, color: string) : Promise<Result<Label, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_label", { projectId, name, color }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateLabel(id: string, name: string, color: string) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_label", { id, name, color }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteLabel(id: string) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_label", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Replace a session's attached labels.
 */
async setSessionLabels(sessionId: string, labelIds: string[]) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_session_labels", { sessionId, labelIds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async sessionDeleteCheck(sessionId: string) : Promise<Result<DeleteCheck, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("session_delete_check", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Permanently delete a session: stop its turn and PTY, tear down its isolated
 * worktree and branch (best-effort, in the background), and remove its rows
 * (events cascade). The worktree survives while sibling sessions share it, and
 * only paths under warden's own worktrees root are ever removed.
 */
async deleteSession(sessionId: string) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_session", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async sendMessage(sessionId: string, text: string, attachments: string[] | null) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_message", { sessionId, text, attachments }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stage files dropped on the composer: copy any outside the working dir into
 * the session's attachments dir, returning records to reference on send.
 */
async attachToSession(sessionId: string, paths: string[]) : Promise<Result<Attachment[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("attach_to_session", { sessionId, paths }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelSession(sessionId: string) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_session", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Approve denied tool patterns for a session and resume the turn. For
 * OpenCode the turn is still alive, blocked on the ask — approving replies to
 * it server-side and the turn continues on its own.
 */
async approveTools(sessionId: string, patterns: string[]) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("approve_tools", { sessionId, patterns }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Reject a pending tool ask. Only OpenCode has a live ask to answer — a
 * Claude denial already ended the turn, so dismissing is purely client-side
 * and never reaches here.
 */
async rejectTools(sessionId: string) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reject_tools", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Approve the agent's plan: leave `plan` mode for `acceptEdits` and resume so
 * the agent implements it. The persistent process is killed inside
 * `resume_with`, so it respawns with the new permission mode.
 */
async approvePlan(sessionId: string) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("approve_plan", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List a session's context sources (files, dirs, saved text), in order.
 */
async listContextSources(sessionId: string) : Promise<Result<SessionContextSource[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_context_sources", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Append a context source to a session and drop its warm process so the next
 * turn picks up the new context.
 */
async addContextSource(sessionId: string, source: ContextSource) : Promise<Result<SessionContextSource, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_context_source", { sessionId, source }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Remove a context source from a session.
 */
async removeContextSource(sessionId: string, id: string) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_context_source", { sessionId, id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Enable or disable a context source without removing it.
 */
async setContextSourceEnabled(sessionId: string, id: string, enabled: boolean) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_context_source_enabled", { sessionId, id, enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Git status for every root of a session. The primary root reads from the
 * session's `working_dir` (which may be an isolated worktree); other roots read
 * from their project path. Non-git roots come back zeroed rather than erroring.
 */
async sessionGitStatus(sessionId: string) : Promise<Result<RepoStatus[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("session_git_status", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The browsable `https` URL for a repo path's `origin` remote, or `None` when
 * there's no recognizable remote. Powers the header's "open repo" button.
 */
async repoBrowseUrl(path: string) : Promise<Result<string | null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("repo_browse_url", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Push the session's worktree branch to its origin remote (publishing or
 * updating the upstream tracking branch).
 */
async pushSession(sessionId: string) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("push_session", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Pull the latest upstream commits onto the session's branch (fetch + merge).
 * Reports clashing files on conflict, like `sync_worktree`.
 */
async pullSession(sessionId: string) : Promise<Result<SyncOutcome, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pull_session", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Every change a session has made since it forked, for the diff view. Empty
 * when the session has no base commit (non-git or merged).
 */
async getSessionDiff(sessionId: string) : Promise<Result<DiffFile[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_session_diff", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Full before/after contents of one changed file, for the diff tab's
 * side-by-side rendering.
 */
async getSessionFileVersions(sessionId: string, path: string) : Promise<Result<FileVersions, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_session_file_versions", { sessionId, path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The commits a session has made on its branch since it forked from base.
 */
async getSessionCommits(sessionId: string, limit: number | null) : Promise<Result<Commit[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_session_commits", { sessionId, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Bring a session's worktree up to date with the latest base branch (fetch +
 * rebase by default). Aborts cleanly and reports files on conflict.
 */
async syncWorktree(sessionId: string, mode: string | null) : Promise<Result<SyncOutcome, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("sync_worktree", { sessionId, mode }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async runPlanToCode(projectId: string, task: string, plannerModel: string, coderModel: string) : Promise<Result<PlanToCodeResult, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("run_plan_to_code", { projectId, task, plannerModel, coderModel }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createWorkflow(projectId: string, name: string, graph: WorkflowGraph) : Promise<Result<Workflow, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_workflow", { projectId, name, graph }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getWorkflow(id: string) : Promise<Result<Workflow, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_workflow", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listWorkflows(projectId: string) : Promise<Result<Workflow[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_workflows", { projectId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateWorkflow(id: string, name: string | null, graph: WorkflowGraph | null) : Promise<Result<Workflow, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_workflow", { id, name, graph }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteWorkflow(id: string) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_workflow", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Snapshot the workflow's graph, seed its node runs, and spawn the executor.
 */
async runWorkflow(workflowId: string, groupId: string | null) : Promise<Result<WorkflowRunView, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("run_workflow", { workflowId, groupId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Resume a run paused at a gate: approve to continue past it, or reject to
 * cancel the run.
 */
async resumeWorkflow(runId: string, approve: boolean) : Promise<Result<WorkflowRunView, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resume_workflow", { runId, approve }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Retry a failed or canceled run: every node that didn't finish resets to
 * pending, then the executor re-enters — `done` nodes are skipped, so the run
 * picks up where it stopped, in its original worktree.
 */
async retryWorkflowRun(runId: string) : Promise<Result<WorkflowRunView, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("retry_workflow_run", { runId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Cancel a workflow's latest run: signal the executor, stop the in-flight node
 * session, and settle the run to `Canceled`. No-op if there's no active run.
 */
async cancelWorkflow(workflowId: string) : Promise<Result<WorkflowRunView | null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_workflow", { workflowId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getWorkflowRun(runId: string) : Promise<Result<WorkflowRunView, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_workflow_run", { runId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The workflow's most recent run (node statuses + sessions), or `None`.
 */
async getLatestWorkflowRun(workflowId: string) : Promise<Result<WorkflowRunView | null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_latest_workflow_run", { workflowId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * A workflow's past runs, newest first (run history).
 */
async listWorkflowRuns(workflowId: string, limit: number | null) : Promise<Result<WorkflowRun[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_workflow_runs", { workflowId, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The sessions a workflow's runs have spawned (for the sidebar).
 */
async listWorkflowSessions(workflowId: string) : Promise<Result<Session[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_workflow_sessions", { workflowId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List files in the working directory, honoring .gitignore. Runs on a blocking
 * thread since the walk touches the filesystem.
 */
async listFiles(workingDir: string, max: number | null) : Promise<Result<FileEntry[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_files", { workingDir, max }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List `/`-invocable items: custom commands from `.claude/commands` and skills
 * from `.claude/skills`, both project- and user-level. Names are deduped, with
 * project entries winning over user entries.
 */
async listCommands(workingDir: string) : Promise<Result<SlashCommand[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_commands", { workingDir }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List open issues and PRs for the repo via the `gh` CLI. Returns an empty
 * list (never an error) when gh is unavailable or the dir isn't a gh repo.
 */
async listRepoRefs(workingDir: string) : Promise<Result<RepoRef[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_repo_refs", { workingDir }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Fetch the title and body of a single issue or PR via the `gh` CLI.
 */
async fetchRepoRef(workingDir: string, kind: string, number: number) : Promise<Result<RepoRefBody, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_repo_ref", { workingDir, kind, number }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Open `path` in an external app selected by `target`: `"folder"`,
 * `"terminal"` (the OS default), or an editor id from [`list_open_apps`].
 */
async openIn(target: string, path: string) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_in", { target, path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The editors installed on this machine, in registry order. The folder and
 * terminal targets are always available and not listed here (the terminal
 * opens the OS default).
 */
async listOpenApps() : Promise<Result<OpenApp[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_open_apps") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listProviderStatus() : Promise<Result<ToolStatus[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_provider_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The models the local OpenCode install can run (connected providers only) —
 * the picker's OpenCode pane, since availability is per-account.
 */
async listOpencodeModels() : Promise<Result<OpencodeModel[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_opencode_models") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Install warden's managed copy of a provider CLI (latest version).
 */
async installProvider(id: string) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("install_provider", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Reinstall the managed copy at the latest published version.
 */
async updateProvider(id: string) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_provider", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Choose where a provider's CLI comes from (`auto` | `managed` | `system`),
 * persisting the choice so it survives restarts.
 */
async setProviderSource(id: string, source: string) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_provider_source", { id, source }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async githubStatus() : Promise<Result<ToolStatus, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("github_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Install warden's managed copy of the GitHub CLI (latest version).
 */
async installGithubCli() : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("install_github_cli") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Reinstall the managed GitHub CLI at the latest published version.
 */
async updateGithubCli() : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_github_cli") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Choose where the GitHub CLI comes from (`auto` | `managed` | `system`).
 */
async setGithubSource(source: string) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_github_source", { source }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Commit the session's work, push its branch, and open a pull request against
 * the session's base branch.
 */
async openPullRequest(sessionId: string, title: string, body: string, draft: boolean | null) : Promise<Result<PrInfo, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_pull_request", { sessionId, title, body, draft }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Re-read the session branch's pull request state from GitHub.
 */
async refreshPrStatus(sessionId: string) : Promise<Result<PrInfo | null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("refresh_pr_status", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Rich state of the session's PR — review decision, diff stats, per-check CI
 * rows — fetched lazily when the user hovers the PR chip.
 */
async prDetails(sessionId: string) : Promise<Result<PrDetails | null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pr_details", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Generate a suggested PR title and body from the session branch's changes,
 * for the user to review before opening. Falls back to the session title.
 */
async generatePrContent(sessionId: string) : Promise<Result<PrContent, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("generate_pr_content", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Open PRs in a project's repo, for the review-checkout picker.
 */
async listOpenPrs(projectId: string) : Promise<Result<PrSummary[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_open_prs", { projectId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check out an existing PR into a fresh isolated worktree and open a session on
 * it, for reviewing/running the PR locally.
 */
async checkoutPr(projectId: string, number: number, model: string) : Promise<Result<Session, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("checkout_pr", { projectId, number, model }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Open issues assigned to the user in one repo. Soft-fails to empty (no
 * remote / unauthenticated) so multi-repo aggregation degrades per repo.
 */
async listMyIssues(projectId: string) : Promise<Result<GhIssue[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_my_issues", { projectId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Comments on one issue, fetched lazily for the detail view.
 */
async githubIssueComments(projectId: string, number: number) : Promise<Result<GhIssueComment[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("github_issue_comments", { projectId, number }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Validate a personal API key against Linear and, on success, store it in the
 * OS keychain and do a best-effort initial sync. Returns the authenticated user.
 */
async linearConnect(key: string) : Promise<Result<Viewer, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("linear_connect", { key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Forget the stored API key and clear the cached inbox.
 */
async linearDisconnect() : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("linear_disconnect") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Whether a Linear key is stored (no network call).
 */
async linearStatus() : Promise<Result<LinearStatus, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("linear_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The cached inbox (assigned issues), read from the local DB — instant, offline.
 */
async linearCachedIssues() : Promise<Result<LinearIssue[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("linear_cached_issues") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Force a sync against Linear and return the freshened cache.
 */
async linearSyncNow() : Promise<Result<LinearIssue[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("linear_sync_now") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Comments for one issue, fetched live when the peek panel opens. Not cached:
 * keeping comments out of the poll query keeps its complexity flat, and
 * fetching on open means they are never stale.
 */
async linearIssueComments(issueId: string) : Promise<Result<LinearComment[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("linear_issue_comments", { issueId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Move an issue to its team's primary "started" state (writeback on
 * send-to-agent). Freshens the cache afterwards so the inbox reflects it.
 */
async linearStartIssue(issueId: string, teamId: string) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("linear_start_issue", { issueId, teamId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Teams (with their projects) visible to the user — for the binding picker.
 */
async linearTeams() : Promise<Result<LinearTeam[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("linear_teams") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * A project's Linear binding from its `.warden/config.json`, if any.
 */
async linearBinding(projectId: string) : Promise<Result<LinearBinding | null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("linear_binding", { projectId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Every known project that carries a Linear binding — for preselecting the
 * repo when sending an issue to an agent.
 */
async linearBindings() : Promise<Result<ProjectLinearBinding[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("linear_bindings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Write (or remove, with `None`) a project's Linear binding.
 */
async linearSetBinding(projectId: string, binding: LinearBinding | null) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("linear_set_binding", { projectId, binding }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Frontend focus reporting: window focus/blur events land here.
 */
async setAppFocusState(focused: boolean) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_app_focus_state", { focused }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Spawn a PTY in `working_dir` (the session's root) and stream its output over
 * `on_output`. The terminal id is the session id; the launch command is derived
 * from the persisted session, so a native CLI session relaunches (and resumes)
 * its provider across app restarts instead of falling back to a bare shell.
 */
async startTerminal(onOutput: TAURI_CHANNEL<TerminalEvent>, terminalId: string, workingDir: string, cols: number, rows: number) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_terminal", { onOutput, terminalId, workingDir, cols, rows }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async terminalWrite(terminalId: string, data: string) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("terminal_write", { terminalId, data }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async terminalResize(terminalId: string, cols: number, rows: number) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("terminal_resize", { terminalId, cols, rows }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopTerminal(terminalId: string) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_terminal", { terminalId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AgentTaskConfig = { intent?: Intent; model: string; effort: EffortLevel; 
/**
 * The feature description (Plan/Custom) or optional extra instructions.
 */
prompt?: string; 
/**
 * Open the per-run worktree on a named branch; else `wf/<run>`.
 */
branchHint?: string | null; 
/**
 * Mode override — only honored for `Custom`; other intents always run
 * under their intent's mode so read-only nodes stay read-only.
 */
permissionMode?: PermissionMode | null }
/**
 * A staged attachment ready to reference in a message.
 */
export type Attachment = { id: string; name: string; 
/**
 * The path the agent reads — in place, or the staged copy.
 */
path: string; isImage: boolean; isDir: boolean }
/**
 * Which agent backend powers a session. This enum is the seam where providers
 * plug in; each variant has an adapter under `crate::providers`.
 */
export type Backend = "claude" | "codex" | "opencode"
/**
 * Aggregate CI-check state for a session's pull request, distilled from `gh`'s
 * `statusCheckRollup`. Absent when the PR has no checks.
 */
export type CheckStatus = "success" | "failure" | "pending"
/**
 * A commit made on the session's branch since it forked from base.
 */
export type Commit = { sha: string; subject: string; author: string; date: string }
/**
 * A piece of context injected into an agent's system prompt for a session.
 * Phase 1 covers manual sources; GitHub refs and node-graph outputs come later.
 */
export type ContextSource = 
/**
 * A single file: its directory is made accessible and it's referenced by
 * path in the prompt.
 */
{ kind: "file"; path: string } | 
/**
 * A directory added to the agent's accessible roots.
 */
{ kind: "dir"; path: string } | 
/**
 * A saved text snippet inlined into the prompt.
 */
{ kind: "text"; label: string; body: string } | 
/**
 * The latest assistant output of another session (e.g. an upstream
 * workflow node), resolved to text at turn time and injected as context.
 */
{ kind: "nodeOutput"; session_id: string; label: string | null }
/**
 * Optional fields for `create_session`. Grouped into a struct so the command
 * stays within specta's 10-parameter limit while remaining fully expressive.
 */
export type CreateSessionOptions = { groupId: string | null; permissionMode: string | null; effort: string | null; role: string | null; kind: string | null; backend: string | null; isolate: boolean | null; nativeCommand: string | null; 
/**
 * Run in this exact directory instead of provisioning one — e.g. a shell
 * opened inside another session's worktree. Implies no isolation.
 */
workingDir: string | null; 
/**
 * Linear issue this session works on; drives writeback on PR open/merge.
 */
linearIssueId: string | null; 
/**
 * Worktree branch name (e.g. `feature/WAR-123` derived from an issue).
 */
branchHint: string | null }
/**
 * What deleting a session would destroy, so the UI can ask before — instead of
 * force-deleting work. All zeros when nothing is at risk: checkout sessions
 * (nothing is removed), merged sessions (already cleaned), shared worktrees
 * (kept for the siblings).
 */
export type DeleteCheck = { 
/**
 * Files with uncommitted changes in the worktree (untracked included).
 */
dirtyFiles: number; 
/**
 * Commits on the session's branch its base doesn't have.
 */
unmergedCommits: number; 
/**
 * Other sessions running in the same worktree — it stays while they exist.
 */
sharedSessions: number }
/**
 * One changed file's stats and unified-diff patch (vs the session's base).
 */
export type DiffFile = { path: string; added: number; removed: number; binary: boolean; patch: string }
/**
 * Reasoning effort for a session. `low..max` are `claude --effort` tokens;
 * `Ultracode` is a Claude Code session setting on top (xhigh effort plus
 * workflow orchestration) — each adapter maps it to what its CLI accepts.
 */
export type EffortLevel = "low" | "medium" | "high" | "xhigh" | "max" | "ultracode"
/**
 * A persisted, ordered event in a session's append-only log. The transcript
 * you render today and the cross-agent thread you render later are both just
 * projections over this log.
 */
export type EventRecord = (
/**
 * Emitted once the CLI confirms the conversation has started.
 */
{ type: "session_init"; model: string | null; tools: string[] } | 
/**
 * A message we sent on the user's behalf.
 */
{ type: "user_message"; text: string } | 
/**
 * A finalized assistant text block. `parent_tool_use_id` is set for a
 * subagent's narration so the UI can fold it under the spawning Task.
 */
{ type: "assistant_text"; text: string; parent_tool_use_id?: string | null } | 
/**
 * A streaming text fragment. Transient — never persisted, UI-only sugar.
 */
{ type: "text_delta"; text: string } | 
/**
 * Extended-thinking content.
 */
{ type: "thinking"; text: string } | 
/**
 * The agent invoked a tool. `parent_tool_use_id` is set when the call ran
 * inside a subagent (Task/Agent) — it points at that Task's tool_use id, so
 * the UI can nest a subagent's activity under it.
 */
{ type: "tool_use"; id: string; name: string; input: JsonValue; parent_tool_use_id?: string | null } | 
/**
 * The result of a tool invocation.
 */
{ type: "tool_result"; tool_use_id: string; content: string; is_error: boolean } | 
/**
 * The turn completed.
 */
{ type: "result"; is_error: boolean; cost_usd: number | null; duration_ms: number | null; num_turns: number | null; usage?: TokenUsage | null } | 
/**
 * One or more tool calls were denied for lack of permission. Approving
 * resumes the turn with those tools added to the session's allowlist.
 */
{ type: "permission_request"; denials: ToolDenial[] } | 
/**
 * A warden-level annotation (e.g. a handoff between sessions).
 */
{ type: "notice"; text: string } | 
/**
 * A turn-level failure.
 */
{ type: "error"; message: string }) & { id: string; sessionId: string; seq: number; ts: string }
export type FileEntry = { 
/**
 * Path relative to the working directory, using forward slashes.
 */
path: string; name: string }
/**
 * One file's full before/after contents, for a rich (side-by-side) diff.
 */
export type FileVersions = { 
/**
 * Contents at the base commit; `None` when the file was added.
 */
oldText: string | null; 
/**
 * Working-tree contents; `None` when the file was deleted.
 */
newText: string | null }
/**
 * An open issue assigned to the user, from `gh issue list`.
 */
export type GhIssue = { number: number; title: string; url: string; body: string; labels: string[]; author: string; updatedAt: string }
export type GhIssueComment = { author: string; body: string; createdAt: string }
/**
 * The top-level workspace: a named set of project roots plus a saved pane
 * layout. Sessions are opened against a group and may pull any of its roots
 * into context.
 */
export type Group = { id: string; name: string; 
/**
 * Opaque JSON describing the saved pane layout (grid mode + pane→session
 * assignments). The backend stores it verbatim; only the UI interprets it.
 */
layout: string; createdAt: string }
/**
 * What an agent node does. The intent carries a built-in instruction and the
 * right read/write posture, so downstream nodes need no hand-written task —
 * the edge supplies the content (the upstream plan/review/diff as context).
 */
export type Intent = 
/**
 * Research + produce an implementation plan (read-only).
 */
"plan" | 
/**
 * Implement the upstream plan (edits code).
 */
"code" | 
/**
 * Review the worktree diff and report issues (read-only).
 */
"review" | 
/**
 * Apply the upstream review's feedback (edits code).
 */
"revise" | 
/**
 * Free-form agent — the prompt is the whole task (default for legacy data).
 */
"custom"
/**
 * Serializable error for the Tauri IPC boundary. Commands return this so
 * specta can generate the TypeScript type; internally we use AppError.
 */
export type IpcError = string
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
/**
 * A per-project label (GitHub-style) that can be attached to sessions.
 */
export type Label = { id: string; projectId: string; name: string; 
/**
 * A palette token the frontend maps to fill/text/ring classes.
 */
color: string; createdAt: string }
export type LinearBinding = { teamId: string; projectId: string | null }
export type LinearComment = { id: string; body: string; createdAt: string; user: LinearUserRef | null }
export type LinearIssue = { id: string; identifier: string; title: string; description: string | null; priority: number; url: string;
/**
 * Linear's workspace-configured git branch name for the issue.
 * Defaulted so payloads cached before this field existed still parse.
 */
branchName: string; updatedAt: string; state: LinearState; assignee: LinearUserRef | null; team: LinearTeamRef; project: LinearProjectRef | null; labels: string[] }
export type LinearProjectRef = { id: string; name: string }
export type LinearState = { id: string; name: string; color: string; 
/**
 * Linear state category: backlog | unstarted | started | completed | canceled.
 */
type: string }
/**
 * Connection state for the Tasks UI.
 */
export type LinearStatus = { connected: boolean }
export type LinearTeam = { id: string; key: string; name: string; projects: LinearProjectRef[] }
export type LinearTeamRef = { id: string; key: string; name: string }
export type LinearUserRef = { id: string; name: string; email: string | null; avatarUrl: string | null }
/**
 * The node's behavior.
 */
export type NodeKind = 
/**
 * Topological root; synthesized if absent. Carries no agent.
 */
{ type: "start" } | 
/**
 * Run an agent task — its `intent` defines what it does.
 */
({ type: "agentTask" } & AgentTaskConfig) | 
/**
 * Pause the run for the user's sign-off. No config — a gate is just a
 * human checkpoint between agent steps; you click Approve or Reject.
 */
{ type: "gate" }
export type NodePosition = { x: number; y: number }
export type NodeRunStatus = "pending" | "running" | "done" | "failed" | "skipped" | 
/**
 * A gate awaiting human approval.
 */
"paused" | 
/**
 * The agent asked a question and is waiting for the user's reply.
 */
"awaitingInput"
/**
 * One installed editor, surfaced to the "open in…" menu.
 */
export type OpenApp = { id: string; name: string }
/**
 * One selectable OpenCode model for the picker.
 */
export type OpencodeModel = { 
/**
 * Picker model id, prefixed so it routes to the OpenCode backend
 * (`opencode/<model>` for Zen, `opencode/<provider>/<model>` otherwise).
 */
id: string; 
/**
 * The `provider/model` identifier as OpenCode prints it.
 */
label: string }
/**
 * Permission posture handed to the agent CLI. Sessions are worktree-isolated,
 * so `BypassPermissions` is the default for autonomous, prompt-free turns.
 */
export type PermissionMode = "acceptEdits" | "bypassPermissions" | "plan" | "default"
/**
 * The pair of sessions a plan → code handoff produces.
 */
export type PlanToCodeResult = { planner: Session; coder: Session }
/**
 * One CI check (check run or commit status) on a PR's head commit.
 */
export type PrCheck = { name: string; state: PrCheckState; url: string | null; startedAt: string | null; completedAt: string | null }
/**
 * Per-state tallies of a PR's CI checks, persisted alongside the aggregate
 * rollup so list views can render counts without shelling out to `gh`.
 */
export type PrCheckCounts = { passed: number; failed: number; pending: number; skipped: number }
/**
 * One CI check's outcome on a PR, for the hover card's per-check rows.
 */
export type PrCheckState = "success" | "failure" | "pending" | "skipped" | "cancelled"
/**
 * A generated PR title and body, for the user to review before opening.
 */
export type PrContent = { title: string; body: string }
/**
 * Richer PR state for the hover card: review decision, diff stats, and the
 * individual CI checks behind the aggregate glyph.
 */
export type PrDetails = { number: number; url: string; 
/**
 * GitHub's PR state: `OPEN`, `MERGED`, or `CLOSED`.
 */
state: string; title: string; isDraft: boolean; 
/**
 * `APPROVED`, `CHANGES_REQUESTED`, or `REVIEW_REQUIRED` (empty when the
 * repo requires no review).
 */
reviewDecision: string | null; additions: number; deletions: number; updatedAt: string | null; checks: PrCheck[] }
/**
 * A pull request's identity and state, as surfaced to the UI.
 */
export type PrInfo = { number: number; url: string; 
/**
 * GitHub's PR state: `OPEN`, `MERGED`, or `CLOSED`.
 */
state: string; title: string; isDraft: boolean; 
/**
 * `APPROVED`, `CHANGES_REQUESTED`, or `REVIEW_REQUIRED` (absent when the
 * repo requires no review).
 */
reviewDecision: string | null; 
/**
 * Aggregate CI-check state, or `None` when the PR has no checks.
 */
checkStatus: CheckStatus | null; 
/**
 * Per-state CI check tallies, `None` when the PR has no checks.
 */
checkCounts: PrCheckCounts | null }
/**
 * An open PR in a repo, for the review-checkout picker.
 */
export type PrSummary = { number: number; title: string; author: string; headRef: string }
/**
 * A project is a project root the user has opened. When it is a git
 * repository, sessions get isolated worktrees; otherwise they run in-place.
 */
export type Project = { id: string; name: string; path: string; isGit: boolean; createdAt: string }
/**
 * A project's labels plus which sessions each is attached to — one round-trip
 * for the folder view. `assignments` maps a session id to its label ids.
 */
export type ProjectLabels = { labels: Label[]; assignments: Partial<{ [key in string]: string[] }> }
export type ProjectLinearBinding = { projectId: string; binding: LinearBinding }
export type RepoComment = { author: string; body: string }
export type RepoRef = { number: number; title: string; 
/**
 * "issue" or "pr".
 */
kind: string }
export type RepoRefBody = { title: string; body: string; comments: RepoComment[] }
/**
 * Branch and divergence summary for one of a session's repo roots.
 */
export type RepoStatus = { projectId: string; name: string; path: string; isPrimary: boolean; isGit: boolean; branch: string | null; ahead: number; behind: number; 
/**
 * Lines changed: everything since the session's base for the primary root
 * (committed + uncommitted), uncommitted-only for other roots.
 */
added: number; removed: number; 
/**
 * Whether this root's repo has a remote — i.e. a PR can be opened from it.
 */
hasRemote: boolean }
export type RunStatus = "pending" | "running" | "paused" | "completed" | "failed" | "canceled"
/**
 * A single agent session — one tab in the browser. Carries everything needed
 * to resume the underlying CLI conversation and to render its state.
 */
export type Session = { id: string; groupId: string; 
/**
 * The session's primary repo — where its agent runs. Additional roots are
 * tracked in `session_roots` and handed to the CLI as extra directories.
 */
projectId: string; title: string; kind: SessionKind; backend: Backend; model: string; permissionMode: PermissionMode; effort: EffortLevel; status: SessionStatus; role: SessionRole; 
/**
 * True while the title is still auto-assigned, so background naming may
 * replace it. Set false once the user renames or auto-naming completes.
 */
autoNamed: boolean; 
/**
 * The CLI conversation id we own (passed as `--session-id`, then `--resume`).
 */
agentSessionId: string; 
/**
 * For a native CLI terminal, the provider program to launch (`claude`/`codex`)
 * instead of the shell. `None` for plain shell terminals and agent sessions.
 */
terminalCommand: string | null; 
/**
 * Whether this terminal's CLI has been launched at least once — drives the
 * switch from "start a new conversation" to "resume the existing one".
 */
terminalStarted: boolean; 
/**
 * The provider's own conversation id, recovered after first launch so the
 * terminal resumes that exact session. Used for Codex, which assigns its id
 * (Claude pins `agent_session_id` up front and resumes by that instead).
 */
terminalResumeId: string | null; 
/**
 * Absolute path the agent runs in (an isolated worktree, or the repo root).
 */
workingDir: string; branch: string | null; baseSha: string | null; 
/**
 * The repo branch an isolated session merges back into.
 */
baseBranch: string | null; isIsolated: boolean; 
/**
 * Worktree setup-commands lifecycle; `None` when none are configured.
 */
setupStatus: SetupStatus | null; 
/**
 * Tail of the failing setup output, when `setup_status` is `Failed`.
 */
setupError: string | null; 
/**
 * Tool patterns the user has approved for this session (`--allowedTools`),
 * accumulated as denied tools are approved.
 */
allowedTools: string[]; turns: number; costUsd: number; 
/**
 * Set when this session was produced by a handoff from another session.
 */
parentId: string | null; 
/**
 * Set when a workflow run spawned this session (groups it under the
 * workflow in the sidebar).
 */
workflowId: string | null; 
/**
 * Linear issue this session was spawned from; drives writeback on PR
 * open (attachment) and merge (completed state).
 */
linearIssueId: string | null; 
/**
 * When the session's branch was merged back into its base — `None` until
 * then. A merged session's worktree is gone, so it becomes read-only.
 */
mergedAt: string | null; 
/**
 * The open pull request for this session's branch, once one is created.
 */
prNumber: number | null; prUrl: string | null; 
/**
 * GitHub's PR state (`OPEN`/`MERGED`/`CLOSED`), refreshed by polling.
 */
prState: string | null; 
/**
 * Aggregate CI-check state for the PR, and when it was last polled (epoch s).
 */
prCheckStatus: CheckStatus | null; prCheckedAt: number | null; prIsDraft: boolean; 
/**
 * GitHub's review decision (`APPROVED`/`CHANGES_REQUESTED`/`REVIEW_REQUIRED`),
 * absent when the repo requires no review.
 */
prReviewDecision: string | null; 
/**
 * Per-state CI check tallies, `None` when the PR has no checks.
 */
prCheckCounts: PrCheckCounts | null; 
/**
 * Pinned sessions sort to the top of the folder's session list.
 */
pinned: boolean; createdAt: string; updatedAt: string }
/**
 * A persisted, ordered, toggleable context source on a session.
 */
export type SessionContextSource = { id: string; sessionId: string; position: number; enabled: boolean; source: ContextSource }
/**
 * Whether a session is a headless agent (stream-json adapter) or an
 * interactive terminal running the native `claude` TUI in a PTY.
 */
export type SessionKind = "agent" | "terminal"
/**
 * The role a session plays inside a recipe. Plain sessions are `Chat`; the
 * plan→code handoff produces a `Planner` and a `Coder`.
 */
export type SessionRole = "chat" | "planner" | "coder"
/**
 * Lifecycle state of a session.
 */
export type SessionStatus = "idle" | "running" | "error"
/**
 * Lifecycle of the worktree setup commands run for a session. Absent when the
 * repo configures none.
 */
export type SetupStatus = "running" | "failed" | "done"
export type SlashCommand = { name: string; description: string | null; 
/**
 * "project" or "user".
 */
scope: string }
/**
 * Result of syncing a worktree with its base branch.
 */
export type SyncOutcome = { status: "synced" } | { status: "conflict"; files: string[] }
export type TAURI_CHANNEL<TSend> = null
/**
 * Streamed from a terminal's PTY to the frontend over a Tauri channel.
 */
export type TerminalEvent = { event: "output"; data: string } | { event: "exit"; code: number | null }
/**
 * Token accounting for a turn, mirrored from the model's `usage` report. The
 * input side plus cache reads/writes approximates the context-window fill.
 */
export type TokenUsage = { input_tokens: number; output_tokens: number; cache_read_input_tokens?: number; cache_creation_input_tokens?: number }
/**
 * A tool call the CLI denied for lack of permission. `pattern` is the
 * `--allowedTools` token that would permit it (e.g. `Bash(echo hi)` or `Read`).
 */
export type ToolDenial = { toolName: string; pattern: string; input: JsonValue }
/**
 * A tool's install/version/auth snapshot, surfaced to the UI. `authed` and the
 * latest-version fields are filled by the owning domain (see [`base_status`] and
 * [`fill_latest`]).
 */
export type ToolStatus = { id: string; name: string; 
/**
 * User's source preference: `auto` | `managed` | `system`.
 */
source: string; 
/**
 * Whether the effective (resolved) binary is present and runnable.
 */
installed: boolean; version: string | null; 
/**
 * Absolute path of the effective binary.
 */
path: string | null; authed: boolean; systemDetected: boolean; managedInstalled: boolean; managedVersion: string | null; latestVersion: string | null; updateAvailable: boolean }
export type Viewer = { id: string; name: string; email: string | null }
/**
 * A persisted workflow definition.
 */
export type Workflow = { id: string; projectId: string; name: string; graph: WorkflowGraph; createdAt: string; updatedAt: string }
export type WorkflowEdge = { id: string; source: string; target: string }
export type WorkflowGraph = { nodes?: WorkflowNode[]; edges?: WorkflowEdge[] }
export type WorkflowNode = { id: string; label?: string; kind: NodeKind; 
/**
 * Canvas position — carried for the editor, ignored by the executor.
 */
position?: NodePosition | null }
/**
 * Per-node execution state, overlaying the graph (the node's session row stays
 * the source of truth for transcript/cost/status).
 */
export type WorkflowNodeRun = { runId: string; nodeId: string; status: NodeRunStatus; sessionId: string | null; output: string | null; error: string | null }
/**
 * A single execution of a workflow.
 */
export type WorkflowRun = { id: string; workflowId: string | null; projectId: string; groupId: string; status: RunStatus; error: string | null; createdAt: string; updatedAt: string }
export type WorkflowRunView = { run: WorkflowRun; nodes: WorkflowNodeRun[] }
/**
 * The `worktrees` section: lifecycle commands for isolated worktrees.
 */
export type WorktreeConfig = { 
/**
 * Commands run in a fresh worktree right after it is created (e.g.
 * `pnpm install`, copying `.env`). Joined with `&&`, so the first
 * failure stops the chain.
 */
setup: string[]; 
/**
 * Commands run in a worktree just before it is removed.
 */
teardown: string[] }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
